'use client';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabaseClient';
import { Timer } from '@/components/Timer';
import type { Quiz, Question } from '@/types/quiz';

export default function PlayPage() {
  const router = useRouter();
  const [quiz, setQuiz] = useState<Quiz | null>(null); const [question, setQuestion] = useState<Question | null>(null); const [studentId, setStudentId] = useState(''); const [studentName, setStudentName] = useState(''); const [selected, setSelected] = useState(''); const [result, setResult] = useState<{correct:boolean;points:number}|null>(null); const [timeUp, setTimeUp] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const loadQuestion = useCallback(async (id:string) => { const r=await fetch(`/api/quizzes/${id}/question`,{cache:'no-store'}); if(r.ok) setQuestion((await r.json()).question); }, []);
  useEffect(() => {
    const id=localStorage.getItem('cq-student-quiz'); const sid=localStorage.getItem('cq-student-id'); const name=localStorage.getItem('cq-student-name');
    if(!id || !sid || !name){ router.replace('/join'); return; } setStudentId(sid); setStudentName(name);
    supabase.from('quizzes').select('*').eq('id',id).single().then(({data})=>{ if(!data){router.replace('/join');return;} setQuiz(data as Quiz); loadQuestion(id); setLoading(false); });
    const channel=supabase.channel(`student-${id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'quizzes',filter:`id=eq.${id}`},(payload)=>{ const next=payload.new as Quiz; setQuiz(next); setSelected(''); setResult(null); setTimeUp(false); loadQuestion(id); if(next.status==='finished') router.push(`/results?quiz=${id}`); }).subscribe();
    return()=>{supabase.removeChannel(channel)};
  },[loadQuestion,router]);
  async function answer(letter:string){ if(!quiz || !question || selected || result || timeUp) return; setSelected(letter); try { const r=await fetch(`/api/quizzes/${quiz.id}/answer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId,selectedAnswer:letter})}); const d=await r.json(); if(!r.ok){ if(r.status===409 && d.error?.includes("Time")) setTimeUp(true); else setError(d.error ?? 'Unable to submit answer.'); setSelected(''); return; } setResult({correct:d.correct,points:d.points}); } catch { setError('Unable to connect to quiz server.'); setSelected(''); } }
  if(loading || !quiz) return <main className="quiz-shell flex min-h-screen items-center justify-center"><div className="text-slate-300">Loading quiz...</div></main>;
  if(quiz.status==='waiting') return <main className="quiz-shell flex min-h-screen items-center justify-center p-5"><div className="card w-full max-w-lg p-8 text-center"><div className="text-cyan-300 font-black tracking-widest">YOU'RE IN!</div><h1 className="mt-3 text-3xl font-black">{quiz.title}</h1><p className="mt-4 text-slate-400">Player</p><div className="text-xl font-bold">{studentName}</div><div className="mt-8 rounded-2xl bg-slate-900 p-5 text-slate-300">Waiting for the host to start the quiz...</div></div></main>;
  const options=[question?.option_a,question?.option_b,question?.option_c,question?.option_d];
  return <main className="quiz-shell min-h-screen p-4 md:p-8"><div className="mx-auto max-w-3xl"><header className="mb-6 flex items-center justify-between"><div><div className="text-xs font-black tracking-widest text-cyan-300">CLASSROOM QUIZ</div><div className="font-bold">{studentName}</div></div><div className="text-right"><div className="text-xs text-slate-400">QUESTION</div><div className="font-black">{quiz.current_question+1}</div></div></header><section className="card p-6 md:p-8"><div className="mb-6 flex items-center justify-between"><div className="text-sm text-slate-400">Answer quickly for more points.</div>{question && <Timer startTime={quiz.question_start_time} seconds={question.time_limit} onExpire={()=>{if(!selected&&!result)setTimeUp(true)}} />}</div><h1 className="text-2xl font-black leading-tight md:text-4xl">{question?.question}</h1>{error&&<div className="mt-4 rounded-xl bg-red-950/50 p-3 text-red-200">{error}</div>}<div className="mt-7 grid gap-3 md:grid-cols-2">{options.map((option,i)=><button key={i} className={`answer-card ${selected===String.fromCharCode(65+i)?'selected':''}`} disabled={Boolean(selected||result||timeUp||!question)} onClick={()=>answer(String.fromCharCode(65+i))}><span className="mr-3 inline-flex h-8 w-8 items-center justify-center rounded-lg bg-cyan-400/10 font-black text-cyan-300">{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{result&&<div className={`mt-6 rounded-2xl p-5 text-center ${result.correct?'bg-emerald-950/50 text-emerald-200':'bg-red-950/50 text-red-200'}`}><div className="text-2xl font-black">{result.correct?'Correct!':'Wrong answer'}</div><div className="mt-1">+{result.points} points</div></div>}{timeUp&&<div className="mt-6 rounded-2xl bg-amber-950/50 p-5 text-center text-amber-200"><div className="text-2xl font-black">Time's Up</div><div>Wait for the host to move on.</div></div>}</section></div></main>;
}
