'use client';
import { useSearchParams, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';

export default function JoinPage() {
  const params = useSearchParams(); const router = useRouter();
  const [pin, setPin] = useState(params.get('pin') ?? ''); const [name, setName] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function join() { setError(''); if (!/^\d{6}$/.test(pin)) return setError('Please enter a 6-digit PIN.'); if (!name.trim()) return setError('Please enter your name.'); setBusy(true); try { const r = await fetch('/api/join', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ pin, name }) }); const d=await r.json(); if(!r.ok) throw new Error(d.error); localStorage.setItem('cq-student-id', d.student.id); localStorage.setItem('cq-student-quiz', d.quiz.id); localStorage.setItem('cq-student-name', d.student.name); localStorage.setItem('cq-student-pin', d.quiz.game_pin); router.push('/play'); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to join.'); } finally { setBusy(false); } }
  return <main className="quiz-shell flex min-h-screen items-center justify-center p-5"><div className="card w-full max-w-md p-7"><div className="text-center"><div className="font-black tracking-widest text-cyan-300">CLASSROOM QUIZ</div><h1 className="mt-2 text-4xl font-black">JOIN QUIZ</h1><p className="mt-2 text-slate-400">Student Portal</p></div><div className="mt-8 space-y-4"><label className="block text-sm font-bold">Game PIN<input className="field mt-2 text-center text-2xl tracking-[.3em]" inputMode="numeric" maxLength={6} value={pin} onChange={(e)=>setPin(e.target.value.replace(/\D/g,''))} placeholder="723973" /></label><label className="block text-sm font-bold">Student Name<input className="field mt-2" maxLength={40} value={name} onChange={(e)=>setName(e.target.value)} placeholder="Ayush" /></label>{error && <div className="rounded-xl border border-red-800 bg-red-950/40 p-3 text-sm text-red-200">{error}</div>}<button className="btn-primary w-full" disabled={busy} onClick={join}>{busy ? 'Joining...' : 'JOIN COMPETITION'}</button></div></div></main>;
}
